python - << 'EOF'
from config import CSV_EXPORT_URL, SMART_WEIGHTS, BUY_THRESHOLD
print("CSV_EXPORT_URL:", CSV_EXPORT_URL)
print("SMART_WEIGHTS:", SMART_WEIGHTS)
print("BUY_THRESHOLD:", BUY_THRESHOLD)
EOF
